Repository NamelessGroup/namelessbot, pull requests merged in 2023-02, with the labels that each got.

#63 Improved /vote further
  slashCommands/vote.ts
Labels: enhancement

#66 Improve documentation
  .eslintrc.cjs
  .github/dependabot.yml
  .github/workflows/docs.yml
  .github/workflows/eslint.yml
  .gitignore
  README.md
  assets/audio/Alarm.mp3
  assets/img/mittwoch.jpg
  docs_pages/configuration.md
  index.ts
  lib/aocleaderboardparser.ts
  lib/attendancetracker.ts
  lib/commands.ts
  lib/configmanager.ts
  lib/listeners.ts
  lib/mensaparser.ts
  lib/recurringtask.ts
  lib/taskRunner.ts
  lib/tasks.ts
  lib/truthtable.ts
  listeners/attendanceTrackerButton.ts
  listeners/chatCommands.ts
  listeners/handleSlashCommands.ts
  listeners/koeriSelectionMenu.ts
  listeners/registerSlashCommands.ts
  messageCommands/test.ts
  package.json
  slashCommands/aoc.ts
  slashCommands/koeri.ts
  slashCommands/mensa.ts
  slashCommands/test.ts
  slashCommands/timetable.ts
  slashCommands/truthtable.ts
  slashCommands/vote.ts
  tasks/aoc.ts
  tasks/attendanceTrackerTask.ts
  tasks/mensa.ts
  tasks/reminder.ts
  tsconfig.json
  types.ts
  yarn.lock
Labels: documentation

#78 Replace reviewdog with another report viewer thats working
  .github/workflows/eslint.yml
Labels: bug
